services:
  redis:
    image: redis:7-alpine

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/local.livekit.yaml
    network_mode: host
    volumes:
      - ./local.livekit.yaml:/etc/local.livekit.yaml

  egress:
    image: livekit/egress:latest
    cap_add:
      - SYS_ADMIN
    network_mode: host
    environment:
      - EGRESS_CONFIG_FILE=/etc/local.egress.yaml
    volumes:
      - ./local.egress.yaml:/etc/local.egress.yaml
      - ./recordings:/home/egress/recordings

